- action:
  - alias: Floorlight
    data:
      entity_id: switch.floor_light
    service: switch.turn_on
  alias: Solnedgang
  condition: []
  id: '1504645351270'
  trigger:
  - event: sunset
    offset: 00:15:00
    platform: sun
- action:
  - alias: Tænd køkken lyd
    data:
      entity_id: switch.kitchen_speaker
    service: switch.turn_on
  alias: Køkkentid on
  condition: []
  id: '1504646194795'
  trigger:
  - at: '17:00:00'
    platform: time
- action:
  - alias: sluk køkken lyd
    data:
      entity_id: switch.kitchen_speaker
    service: switch.turn_off
  alias: Køkkentid slut
  condition: []
  id: '1505050831732'
  trigger:
  - at: '19:00'
    platform: time
- action:
  - alias: Sluk Floor Light
    data:
      entity_id: switch.floor_light
    service: switch.turn_off
  alias: Godnat Floor Light
  condition: []
  id: '1505413739031'
  trigger:
  - at: 00:00:00
    platform: time
- alias: Play DR P1
  trigger:
    platform: state
    entity_id: input_select.radio_station2
    to: DR P1
  action:
    service: media_player.play_media
    data:
      entity_id: media_player.living_room_stereo
      media_content_id: http://live-icy.gss.dr.dk:80/A/A03H.mp3
      media_content_type: audio/mp4
  id: 40222b634c9144c995932efdce6c35c3
- alias: Play latest DR P1 Orientering
  trigger:
    platform: state
    entity_id: input_select.radio_station2
    to: DR P1 Orientering
  action:
    service: media_player.play_media
    data_template:
      entity_id: media_player.living_room_stereo
      media_content_id: "{{states.sensor.dr_p1_orientering.state}}"
      media_content_type: "audio/mp4"
  id: 20222b634c9144c995932efdce6c35c3
- alias: Play latest DR P1 Mennesker og medier
  trigger:
    platform: state
    entity_id: input_select.radio_station2
    to: DR P1 Mennesker og medier
  action:
    service: media_player.play_media
    data_template:
      entity_id: media_player.living_room_stereo
      media_content_id: "{{states.sensor.dr_p1_mennesker_og_medier.state}}"
      media_content_type: "audio/mp4"
  id: 10222b634c9144c995932efdce6c35c3
- alias: Play latest DR P1 Verden ifoelge Gram
  trigger:
    platform: state
    entity_id: input_select.radio_station2
    to: DR P1 Verden ifoelge Gram
  action:
    service: media_player.play_media
    data_template:
      entity_id: media_player.living_room_stereo
      media_content_id: "{{states.sensor.dr_p1_verden_i_foelge_gram.state}}"
      media_content_type: "audio/mp4"
  id: 00222b634c9144c995932efdce6c35c3
- id: 3d0a368dcfd34322b52e45010980c26f
  alias: Play DR P6 Beat
  trigger:
  - entity_id: input_select.radio_station2
    platform: state
    to: DR P6 Beat
  action:
  - data:
      entity_id: media_player.living_room_stereo
      media_content_id: http://live-icy.gss.dr.dk:80/A/A29H.mp3
      media_content_type: audio/mp4
    service: media_player.play_media
- alias: Play DR Nyheder
  trigger:
    platform: state
    entity_id: input_select.radio_station2
    to: DR Nyheder
  action:
    service: media_player.play_media
    data:
      entity_id: media_player.living_room_stereo
      media_content_id: http://live-icy.gss.dr.dk:80/A/A02L.mp3
      media_content_type: audio/mp4
  id: 14f51c5baa7a4aff8fa4b0c2d4a9c15f
- id: 3ba5eae78d5542389b7abea477371ae2
  alias: Play Radio24syv
  trigger:
  - entity_id: input_select.radio_station2
    platform: state
    to: Radio24syv
  action:
  - data:
      entity_id: media_player.living_room_stereo
      media_content_id: http://stream.taleradio.dk/web128
      media_content_type: audio/mp4
    service: media_player.play_media
- alias: Stop the Radio Stations
  trigger:
    platform: state
    entity_id: input_select.radio_station2
    to: None
  action:
    service: media_player.turn_off
    data:
      entity_id: media_player.living_room_stereo
  id: b8669a1015d64e489da33d04dc3b64ff
- id: '1510699052058'
  alias: Não na casa
  trigger:
  - entity_id: device_tracker.google_maps_109806200856715302129
    event: leave
    platform: zone
    zone: zone.home
  condition: []
  action:
  - alias: Desliga a cafe
    data:
      entity_id: switch.80040667bcddc20119ad
    service: switch.turn_off
  - alias: Desliga a stereo
    data:
      entity_id: switch.stereo
    service: switch.turn_off
  - data:
      entity_id: media_player.living_room_stereo
    service: media_player.media_stop
- id: '1511775784801'
  alias: Brænd ikke kaffen
  trigger:
  - entity_id: switch.80040667bcddc20119ad
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - delay: 00:27:00
  - alias: Sluk espresso apperat
    data:
      entity_id: switch.80040667bcddc20119ad
    service: switch.turn_off
- action:
  - data:
      entity_id: switch.xmas_tree
    service: switch.turn_on
  alias: Juletræ
  condition: []
  id: '1512469704112'
  trigger:
  - event: sunset
    platform: sun
- action:
  - data:
      entity_id: switch.xmas_tree
    service: switch.turn_off
  alias: Sluk juletræ
  condition: []
  id: '1512469866518'
  trigger:
  - event: sunrise
    offset: 01:00:00
    platform: sun
- action:
  - data:
      entity_id: light.cama
    service: light.turn_off
  - data:
      entity_id: light.loft
    service: light.turn_off
  alias: Turn off lights Naomi
  condition: []
  id: '1515413676404'
  trigger:
  - at: 09:00:00
    platform: time
- id: '1538594491500'
  alias: Turn espresso on via ifttt
  trigger:
  - entity_id: input_boolean.espresso
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      event: espresso_on
    service: ifttt.trigger
- id: '1538594909979'
  alias: Turn espresso off via ifttt
  trigger:
  - entity_id: input_boolean.espresso
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      event: espresso_off
    service: ifttt.trigger
- id: '1538994896282'
  alias: Turn Pavoni on via ifttt
  trigger:
  - entity_id: input_boolean.pavoni
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      event: la_pavoni_on
    service: ifttt.trigger
- id: '1538994905975'
  alias: Turn Pavoni on via ifttt
  trigger:
  - entity_id: input_boolean.pavoni
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      event: la_pavoni_on
    service: ifttt.trigger
- id: '1538994989733'
  alias: Turn Pavoni off via ifttt
  trigger:
  - entity_id: input_boolean.pavoni
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      event: la_pavoni_off
    service: ifttt.trigger
- id: '1538994995891'
  alias: Turn Pavoni off via ifttt
  trigger:
  - entity_id: input_boolean.pavoni
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      event: la_pavoni_off
    service: ifttt.trigger
- id: '1539250840798'
  alias: Middags radioavisen
  trigger:
  - at: '12:00:00'
    platform: time
  condition:
  - condition: zone
    entity_id: device_tracker.google_maps_109806200856715302129_94652d7fc5da
    zone: zone.home
  action:
  - data:
      entity_id: ' automation.play_dr_p1'
    service: automation.trigger
- id: '1539432627835'
  alias: Natlys
  trigger:
  - entity_id: light.67700627dc4f22333a4f
    from: unavailable
    platform: state
    to: available
  condition:
  - after: '21:30:00'
    before: 07:00:00
    condition: time
  action:
  - data:
      data:
        brightness: 70
        entity_id: light.67700627dc4f22333a4f
        rgb_color:
        - 255
        - 0
        - 0
    service: light.turn_on
- id: '1539432632738'
  alias: Natlys
  trigger:
  - entity_id: light.67700627dc4f22333a4f
    from: unavailable
    platform: state
    to: available
  condition:
  - after: '21:30:00'
    before: 07:00:00
    condition: time
  action:
  - data:
      color_name: red
      entity_id: light.67700627dc4f22333a4f
    service: light.turn_on
- id: '1539434017804'
  alias: Dagslys
  trigger:
  - entity_id: light.67700627dc4f22333a4f
    from: unavailable
    platform: state
  condition:
  - after: 07:00:30
    before: '21:29:30'
    condition: time
  action:
  - alias: ''
    data:
      color_name: white
      entity_id: light.67700627dc4f22333a4f
    service: light.turn_on
