## Weather prediction
- platform: yr

## Podcasts
- platform: scrape
  resource: http://www.dr.dk/mu/Feed/orientering.xml?format=podcast&limit=500
  name: DR P1 Orientering
  select: 'enclosure:nth-of-type(1)'
  attribute: url

- platform: scrape
  resource: https://www.dr.dk/mu/Feed/verden-ifoelge-gram.xml?format=podcast&limit=500
  name: DR P1 Verden i foelge Gram
  select: 'enclosure:nth-of-type(1)'
  attribute: url

- platform: scrape
  resource: https://www.dr.dk/mu/Feed/mennesker-og-medier.xml?format=podcast&limit=500
  name: DR P1 Mennesker og medier
  select: 'enclosure:nth-of-type(1)'
  attribute: url

## Prices
- platform: geizhals
  name: qc35_II
  product_id: 1696985
  description: "Bose QC35"
  locale: "DE"

- platform: geizhals
  name: wh1000xm3
  product_id: 1877916
  description: "Sony WH1000XM3"
  locale: "DE"

- platform: template
  sensors:
    yrwthr:
      value_template: '{%set list2 = "0","Clear Sky","Fair","Partly Cloudy","Cloudy","Rain Showers","Rain Showers And Thunder","Sleet Showers","Snow Showers","Rain","Heavy Rain","Heavy Rain And Thunder","Sleet","Snow","Snow And Thunder","Fog","0","0","0","0","Sleet Showers And Thunder","Snow Showers And Thunder","Rain And Thunder","Sleet And Thunder","Light Rain Showers And Thunder","Heavy Rain Showers And Thunder","Light Sleet Showers And Thunder","Heavy Sleet Showers And Thunder","Light Snow Showers And Thunder","Heavy Snow Showers And Thunder","Light Rain And Thunder","Light Sleet And Thunder","Heavy Sleet And Thunder","Light Snow And Thunder","Heavy Snow And Thunder","0","0","0","0","0","Light Rain Showers","Heavy Rain Showers","Light Sleet Showers","Heavy Sleet Showers","Light Snow Showers","Heavy Snow Showers","Light Rain","Light Sleet","Heavy Sleet","Light Snow","Heavy Snow"%}{{list2[states.sensor.yr_symbol.state|int]}}'
      entity_picture_template: "{{ state_attr('sensor.yr_symbol','entity_picture') }}"
